---
title: "p8104_hw1_ps3194"
author: "Pangsibo Shen"
date: "9/19/2020"
output: 
  pdf_document:
  latex_engine: pdflatex
fontsize: 12pt
---

## Problem 1
#### Prove the second half of the DeMorgan's Laws. i.e.

$\\(A \cap B)^{c} = A^{c} \cup B^{c}$

#### solution:
we need to prove that $(A \cap B)^{c} \subset (A^{c} \cup B^{c})$ and $A^{c} \cup B^{c} \subset (A \cap B)^{c}$

$\\(i):$
$\\ \forall x \in (A \cap B)^{c}$ definition of complement
$\\ \Rightarrow x \notin (A\cap B)$ proof by contradiction
$\\ \Rightarrow x \notin A$ or $x \notin B$ definition of complement
$\\ \Rightarrow x \in A^{c}$ or $x \in B^{c}$ definition of union
$\\ \Rightarrow x \in A^{c}$ or $x \in B^{c}$ we get $(A \cap B)^{c} \subset (A^{c} \cup B^{c})$

$\\(ii):$
$\\ \forall x \in A^{c} \cup B^{c}$ definition of union
$\\ \Rightarrow x \in A^{c}$ or $x \in B^c$ definition of complement
$\\ \Rightarrow x \notin A$ or $x \notin B$ proof by contradiction
$\\ \Rightarrow x \notin (A \cap B)$ definition of complement
$\\ \Rightarrow x \in (A \cap B)^c$ we get $A^{c} \cup B^{c} \subset (A \cap B)^{c}$

$\\(i)+(ii)$ by definition of set equality
$\\\Rightarrow (A \cap B)^{c} = A^{c} \cup B^{c}$ complete the proof

## Problem 2
#### Suppose that 3 events $A, B, C$ are defined on sample space $\Omega$. Use union, intersection, and complement operations to represent the following event:
#### (a) both $A$ and $B$ occur but not C
#### solution:
$A \cap B\cap  C^c$

#### (b) at least two events occur
#### solution: 
$(A\cap B)\cup (A \cap C) \cup (B \cap C)$

#### (c) at most one event occurs
#### solution: 
$(A\cap B)^c\cap (A \cap C)^c \cap (B \cap C)^c$

#### (d) exactly one event not occurs
#### solution: 
$[A \cap (B^c \cap C^c)]\cup[B \cap(A^c \cap C^c)]\cup[C\cap(A^c \cap B^c)]$

#### (e) at least one event not occurs
#### solution: 
$(A \cap B \cap C)^c$

## Problem 3
#### $A,B$ are two events defined on sample space $\Omega$. Prove that:

$\\(a)$ if $A \subset B$, then $P(A) \leq P(B)$

#### solution: 

Since $E \subset F$, it follows that we can express $F$ as
$F = E \cup E^cF$ Hence, because $E$ and $E^cF$ are mutually exclusive, we obtain, from Axiom 3 of probability, $P(F) = P(E) + P(E^{c}F)$ which proves the result, since $P(E^{c}F) \geq 0$. 

$\\(b)$ $P(A \cap B^c) = P(A)-P(A \cap B)$

#### solution: 

$\\A$ can be written as the union of the two disjoint events $A \cap B^c$ and $A \cap B$.Hence  $\\(A \cap B^c) \cap (A \cap B) = \emptyset$ and two events are independent. From Axiom 3 of probability, we obtain $\\P(A) = P[(A \cap B^c)\cup (A \cap B)]$
$\\ = P(A \cap B^c)+P(A \cap B)$.
After manipulation we get $P(A \cap B^c) = P(A)-P(A \cap B)$. Thus complete the proof.

## Problem 4
#### Susan took two tests. The probability of her passing at least one test is 0.9. Define events $A$ and $B$ as:
$\\A:$ she passed the first test
$\\B:$ she passed the second test
$\\(a)$suppose the probability of her only passing the second test is 0.4. What is $P(A)$?

#### solution: 

$\\P(A \cup B) = P(A)+ P(B \cap A^c) = 0.9$ 
$\\ P(B \cap A^c)= 0.4$ Hence $P(A) = 0.9 - 0.4 =0.5$

$\\(b)$suppose the probability of her passing the second test is 0.6. What is $P(A \cap B^c)$?

#### solution: 

$\\P(A \cup B) = P(B)+ P(A \cap B^c) = 0.9$
$\\P(B)= 0.6$ Hence $P(A \cap B^c) = P(A \cup B)- P(B) = 0.9-0.6 = 0.3$

## Problem 5
#### A bag has four balls labeled 1,2,3, and 4. Two balls are drawn at random with replacement from the bag and the sum of their number is recorded. Continue the trail. Find the probability that “sum is 3” occurs before “sum is 5”.

#### solution: 
Based on law of Total Probability (LTP), the 
$P(sum \enspace 3 \enspace before \enspace 5) = P(sum \enspace 3 \enspace before \enspace 5|3 \enspace first)*P(3 \enspace first)+\\P(sum \enspace 3 \enspace before \enspace 5|5 \enspace first)*P(5 \enspace first)+\\P(sum \enspace 3 \enspace before \enspace 5|other sum \enspace first)*P(othersum \enspace first) \\= 1*2/16 + 0 + P(sum \enspace 3 \enspace before \enspace 5)*(1-2/16-10/16) \\\Rightarrow P(sum \enspace 3 \enspace before \enspace 5) = 1/3$

## Problem 6(Extra)

#### solution: 

When n = 2, we first need to prove that $P(A_1 \cup A_2) = P(A_1)+P(A_2) - P(A_1 \cap A_2)$
We first have $\\ A_1 \cup A_2 = A_1 \cup (A_1^c \cap A_2)$
$\\ A_1 \cap (A_1^c \cap A_2) =  (A_1 \cap A_1^c) \cap A_2 = \emptyset \cap A_2 = \emptyset$
we then have $\\A_2 = (A_1 \cap A_2)\cup(A_1^c \cap A_2)$
$\\ (A_1 \cap A_2)\cap (A_1^c \cap A_2) = \emptyset$
$\\ P(A_1 \cup A_2) =  P(A_1) + P(A_1^c \cap A_2)$ as one
$\\ P(A_2) = P(A_1 \cap A_2) + P(A_1^c \cap A_2)$ as two
from one minus two we get $\\ P(A_1 \cup A_2) -P(A_2) = P(A_1) - P(A_1 \cap A_2)$
$\\ \Rightarrow P(A_1 \cup A_2) =P(A_1) +P(A_2) - P(A_1 \cap A_2)$ Thus complete the proof for n=2

Now assume for n = k $P(A_1\cup A_2 \cup ...\cup A_k) = \sum^k_{i=1}P(A_i)- \sum^k_{i1<i2}P(A_{i1} \cap A_{i2})+...+(-1)^{k+1}\sum_{i1<i2<...<ik}P(A_{i1} \cap A_{i2} \cap ... \cap A_k)$ and let $B = A_{i1} \cap A_{i2} \cap ... \cap A_k$ then $\\P(B \cup A_{k+1}) = P(B) +P(A_{k+1}) - P(B \cap A_{k+1})$ 

I tried but I have to give up from here : (






